### ISSUE TITLE
plugin failed to install

### ISSUE THREAD

**Issue by kanedo** [circuitdb/pimatic-bh1750#3]
Hi,
i tried to install your plugin via `npm install pimatic-bh1750` and it failed to install with the following error:

```
555 verbose cwd /home/pi/pimatic-app
556 error Linux 4.4.11-v7+
557 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-bh1750"
558 error node v4.4.5
559 error npm  v2.15.5
560 error code ELIFECYCLE
561 error i2c@0.1.4 install: `node-gyp rebuild`
561 error Exit status 1
562 error Failed at the i2c@0.1.4 install script 'node-gyp rebuild'.
562 error This is most likely a problem with the i2c package,
562 error not with npm itself.
562 error Tell the author that this fails on your system:
562 error     node-gyp rebuild
562 error You can get information on how to open an issue for this project with:
562 error     npm bugs i2c
562 error Or if that isn't available, you can get their info via:
562 error
562 error     npm owner ls i2c
562 error There is likely additional logging output above.
563 verbose exit [ 1, true ]
```

this is on a raspberry pi 3 with a current raspbian-lite. I know it says its most likely a problem with i2c but if I try `npm install i2c` in a different folder than pimatic-app it succeeds.

**Comment by kanedo** [comment]
Little update: I created a test project which uses the `bh1750` package to read out the sensor and this works well.

**Comment by circuitdb** [comment]
I just merged a pull request from mwittig and released a new version to npm, can you please test it? I have no sensor wired up at the moment.

**Explanation**:
pimatic-bh1750 was not compatible to pimatic 0.9

Also is depended on a bh1750 versions that depends on i2c version 0.1.4. Most likely _npm install i2c@0.1.4_ will not work on your system. _npm install i2c_ will take version 0.2.3, which installs finew.

Same goes for the version of bh1750. You probably have a newer version of bh1750 which uses i2c version 0.2.1 and not 0.1.4.

So it all comes down to compatibility. This package was just not compatible with pimatic 0.9 yet.

**Comment by kanedo** [comment]
Yes thank you that solved the problem!
